spring:
  application:
    name: graphql-kickstarter

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 5
    #    exception-handlers-enabled: true
    exception-handlers-enabled: false
    tracingEnabled: false
  playground:
    headers:
      Authorization: Bearer TOKEN
      user_id: IDP|Thiago
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    enabled: true
voyager:
  enabled: true